/* ==========================================================================
   KK FASHION — PRODUCT DATA
   Central source of truth for every product on the site.
   Images use a deterministic placeholder service (sample clothing photography)
   so every image always loads — swap the `image` field for real product
   photography when it's available.
   ========================================================================== */

const KK_PRODUCTS = [
  { id: 1, name: "Ivory Draped Anarkali", category: "Ethnic Wear", subCategory: "Women", price: 3499, originalPrice: 4999, discount: 30, rating: 4.6, reviews: 128, sizes: ["S","M","L","XL"], colors: ["Ivory","Beige"], image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&h=1150&q=85", description: "A floor-length Anarkali cut from airy georgette with hand-finished gota trim at the neckline. Falls softly from an empire waist for an effortless silhouette.", material: "Georgette with cotton lining", fit: "Regular fit, floor length", brand: "KK Fashion", care: "Dry clean only", availability: "In Stock", isNew: true, isTrending: true, isFeatured: true },
  { id: 2, name: "Banarasi Silk Saree", category: "Sarees", subCategory: "Women", price: 5999, originalPrice: 8499, discount: 29, rating: 4.8, reviews: 214, sizes: ["Free Size"], colors: ["Black","Beige"], image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&h=1150&q=85", description: "Woven on traditional looms, this Banarasi silk saree carries a zari border and a richly patterned pallu built for occasion wear.", material: "Pure silk with zari work", fit: "5.5m saree with unstitched blouse piece", brand: "KK Fashion", care: "Dry clean only", availability: "In Stock", isNew: false, isTrending: true, isFeatured: true },
  { id: 3, name: "Charcoal Tailored Blazer", category: "Western Wear", subCategory: "Women", price: 4299, originalPrice: 5999, discount: 28, rating: 4.5, reviews: 96, sizes: ["S","M","L","XL"], colors: ["Black","White"], image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&h=1150&q=85", description: "A structured single-breasted blazer with a nipped waist, built to layer over everything from denim to slip dresses.", material: "Polyester-viscose blend", fit: "Tailored fit", brand: "KK Fashion", care: "Dry clean recommended", availability: "In Stock", isNew: true, isTrending: false, isFeatured: true },
  { id: 4, name: "Rose Chikankari Kurti", category: "Kurtis", subCategory: "Women", price: 1899, originalPrice: 2699, discount: 30, rating: 4.4, reviews: 175, sizes: ["S","M","L","XL","XXL"], colors: ["Pink","White"], image: "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&h=1150&q=85", description: "Hand-embroidered chikankari work on breathable cotton, cut in a relaxed A-line silhouette for everyday elegance.", material: "100% cotton", fit: "A-line, regular fit", brand: "KK Fashion", care: "Hand wash cold", availability: "In Stock", isNew: false, isTrending: true, isFeatured: false },
  { id: 5, name: "Emerald Wrap Midi Dress", category: "Dresses", subCategory: "Women", price: 2799, originalPrice: 3999, discount: 30, rating: 4.7, reviews: 142, sizes: ["S","M","L"], colors: ["Black","Pink"], image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&h=1150&q=85", description: "A wrap-front midi dress with a fluid drape and a self-tie waist that defines the silhouette without structure.", material: "Crepe", fit: "Wrap fit, true to size", brand: "KK Fashion", care: "Dry clean only", availability: "In Stock", isNew: true, isTrending: true, isFeatured: true },
  { id: 6, name: "Beige Linen Co-ord Set", category: "Western Wear", subCategory: "Women", price: 2999, originalPrice: 3999, discount: 25, rating: 4.3, reviews: 88, sizes: ["S","M","L","XL"], colors: ["Beige","White"], image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&h=1150&q=85", description: "A relaxed shirt-and-trouser co-ord set in textured linen, designed for warm-weather ease.", material: "Linen blend", fit: "Relaxed fit", brand: "KK Fashion", care: "Machine wash cold", availability: "In Stock", isNew: false, isTrending: false, isFeatured: false },
  { id: 7, name: "Gold Zari Lehenga Choli", category: "Ethnic Wear", subCategory: "Women", price: 8999, originalPrice: 12999, discount: 31, rating: 4.9, reviews: 63, sizes: ["S","M","L","XL"], colors: ["Beige","Pink"], image: "https://images.unsplash.com/photo-1506629905607-d9c297d0f8e0?auto=format&fit=crop&w=900&h=1150&q=85", description: "A festive lehenga set with dense zari embroidery on the choli and a flared, layered skirt built for movement.", material: "Silk blend with net dupatta", fit: "Semi-stitched, customizable", brand: "KK Fashion", care: "Dry clean only", availability: "In Stock", isNew: true, isTrending: true, isFeatured: true },
  { id: 8, name: "Classic White Cotton Shirt", category: "Shirts", subCategory: "Men", price: 1599, originalPrice: 2199, discount: 27, rating: 4.5, reviews: 231, sizes: ["S","M","L","XL","XXL"], colors: ["White"], image: "https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=900&h=1150&q=85", description: "A crisp, tailored cotton shirt with a clean point collar — the everyday foundation piece for a sharp wardrobe.", material: "100% cotton poplin", fit: "Tailored fit", brand: "KK Fashion", care: "Machine wash cold, iron warm", availability: "In Stock", isNew: false, isTrending: true, isFeatured: true },
  { id: 9, name: "Navy Check Casual Shirt", category: "Shirts", subCategory: "Men", price: 1799, originalPrice: 2499, discount: 28, rating: 4.3, reviews: 104, sizes: ["S","M","L","XL"], colors: ["Black","White"], image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&h=1150&q=85", description: "A brushed-cotton check shirt built for cool-weather layering, with a relaxed collar and single chest pocket.", material: "Brushed cotton", fit: "Regular fit", brand: "KK Fashion", care: "Machine wash cold", availability: "In Stock", isNew: true, isTrending: false, isFeatured: false },
  { id: 10, name: "Charcoal Slim Fit Jeans", category: "Jeans", subCategory: "Men", price: 2199, originalPrice: 2999, discount: 27, rating: 4.4, reviews: 189, sizes: ["S","M","L","XL"], colors: ["Black"], image: "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=900&h=1150&q=85", description: "Stretch-denim jeans with a slim leg and a mid-rise waist, engineered to hold shape through the day.", material: "98% cotton, 2% elastane", fit: "Slim fit", brand: "KK Fashion", care: "Machine wash cold, inside out", availability: "In Stock", isNew: false, isTrending: true, isFeatured: false },
  { id: 11, name: "Sandstone Kurta Pyjama Set", category: "Ethnic Wear", subCategory: "Men", price: 2399, originalPrice: 3299, discount: 27, rating: 4.6, reviews: 77, sizes: ["S","M","L","XL","XXL"], colors: ["Beige"], image: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&h=1150&q=85", description: "A straight-cut kurta in raw silk-blend fabric paired with matching pyjama pants, suited to festive occasions.", material: "Silk-cotton blend", fit: "Straight fit", brand: "KK Fashion", care: "Dry clean recommended", availability: "In Stock", isNew: true, isTrending: false, isFeatured: true },
  { id: 12, name: "Olive Bomber Jacket", category: "Western Wear", subCategory: "Men", price: 3599, originalPrice: 4999, discount: 28, rating: 4.5, reviews: 91, sizes: ["S","M","L","XL"], colors: ["Black"], image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&h=1150&q=85", description: "A ribbed-hem bomber jacket in a durable twill shell, cut with room to layer a hoodie underneath.", material: "Cotton twill, polyester lining", fit: "Regular fit", brand: "KK Fashion", care: "Dry clean only", availability: "In Stock", isNew: false, isTrending: true, isFeatured: false },
  { id: 13, name: "Graphite Crew Neck Tee", category: "T-Shirts", subCategory: "Men", price: 799, originalPrice: 1199, discount: 33, rating: 4.2, reviews: 312, sizes: ["S","M","L","XL","XXL"], colors: ["Black","White"], image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&h=1150&q=85", description: "A heavyweight cotton tee with a clean crew neckline — built to keep its shape wash after wash.", material: "220 GSM combed cotton", fit: "Regular fit", brand: "KK Fashion", care: "Machine wash cold", availability: "In Stock", isNew: true, isTrending: true, isFeatured: false },
  { id: 14, name: "Stone Chino Trousers", category: "Western Wear", subCategory: "Men", price: 1999, originalPrice: 2799, discount: 29, rating: 4.3, reviews: 118, sizes: ["S","M","L","XL"], colors: ["Beige"], image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&h=1150&q=85", description: "Slim-tapered chinos in a mid-weight cotton twill, finished with a clean flat front.", material: "Cotton twill", fit: "Slim tapered", brand: "KK Fashion", care: "Machine wash cold", availability: "In Stock", isNew: false, isTrending: false, isFeatured: false },
  { id: 15, name: "Sunshine Cotton Frock", category: "Kids", subCategory: "Kids", price: 999, originalPrice: 1499, discount: 33, rating: 4.6, reviews: 84, sizes: ["S","M","L"], colors: ["Pink","White"], image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&h=1150&q=85", description: "A twirl-friendly cotton frock with a smocked bodice and puffed sleeves, made for all-day play.", material: "100% cotton", fit: "Regular fit", brand: "KK Fashion", care: "Machine wash cold", availability: "In Stock", isNew: true, isTrending: false, isFeatured: true },
  { id: 16, name: "Little Explorer Dungaree Set", category: "Kids", subCategory: "Kids", price: 1299, originalPrice: 1899, discount: 32, rating: 4.5, reviews: 59, sizes: ["S","M","L"], colors: ["Beige","White"], image: "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&h=1150&q=85", description: "A dungaree-and-tee set in durable cotton twill, with adjustable straps that grow with your little one.", material: "Cotton twill", fit: "Regular fit", brand: "KK Fashion", care: "Machine wash cold", availability: "In Stock", isNew: false, isTrending: true, isFeatured: false },
  { id: 17, name: "Printed Kids Ethnic Kurta", category: "Kids", subCategory: "Kids", price: 899, originalPrice: 1299, discount: 31, rating: 4.4, reviews: 46, sizes: ["S","M","L"], colors: ["Pink","Beige"], image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&h=1150&q=85", description: "A block-printed kurta with a mandarin collar, styled for festive family gatherings.", material: "Cotton", fit: "Regular fit", brand: "KK Fashion", care: "Hand wash cold", availability: "In Stock", isNew: true, isTrending: false, isFeatured: false },
  { id: 18, name: "Mustard Bandhani Kurti", category: "Kurtis", subCategory: "Women", price: 1699, originalPrice: 2399, discount: 29, rating: 4.3, reviews: 98, sizes: ["S","M","L","XL"], colors: ["Beige","Pink"], image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&h=1150&q=85", description: "Traditional bandhani tie-dye on soft rayon, cut in a straight silhouette with side slits.", material: "Rayon", fit: "Straight fit", brand: "KK Fashion", care: "Hand wash cold", availability: "In Stock", isNew: false, isTrending: true, isFeatured: false },
  { id: 19, name: "Blush Organza Saree", category: "Sarees", subCategory: "Women", price: 4599, originalPrice: 6499, discount: 29, rating: 4.7, reviews: 71, sizes: ["Free Size"], colors: ["Pink","White"], image: "https://images.unsplash.com/photo-1506629905607-d9c297d0f8e0?auto=format&fit=crop&w=900&h=1150&q=85", description: "Lightweight organza saree with delicate sequin scatter work, designed to catch the light as it moves.", material: "Organza", fit: "5.5m saree with blouse piece", brand: "KK Fashion", care: "Dry clean only", availability: "In Stock", isNew: true, isTrending: false, isFeatured: true },
  { id: 20, name: "Denim Button-Down Dress", category: "Dresses", subCategory: "Women", price: 2199, originalPrice: 2999, discount: 27, rating: 4.2, reviews: 63, sizes: ["S","M","L","XL"], colors: ["Black"], image: "https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=900&h=1150&q=85", description: "A shirt-style denim dress with a belted waist, built for a laid-back weekend uniform.", material: "Cotton denim", fit: "Regular fit", brand: "KK Fashion", care: "Machine wash cold", availability: "In Stock", isNew: false, isTrending: false, isFeatured: false },
  { id: 21, name: "Layered Gold Pendant Set", category: "Accessories", subCategory: "Accessories", price: 1299, originalPrice: 1899, discount: 32, rating: 4.5, reviews: 152, sizes: ["Free Size"], colors: ["Beige"], image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&h=1150&q=85", description: "A layered pendant necklace set finished in a warm gold tone, styled to work with both ethnic and western fits.", material: "Gold-plated brass", fit: "Adjustable chain", brand: "KK Fashion", care: "Keep away from moisture", availability: "In Stock", isNew: true, isTrending: true, isFeatured: false },
  { id: 22, name: "Woven Cane Handbag", category: "Accessories", subCategory: "Accessories", price: 1899, originalPrice: 2599, discount: 27, rating: 4.6, reviews: 67, sizes: ["Free Size"], colors: ["Beige"], image: "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=900&h=1150&q=85", description: "A structured cane handbag with a leather-trimmed handle, sized for essentials without the bulk.", material: "Cane with genuine leather trim", fit: "One size", brand: "KK Fashion", care: "Wipe clean with dry cloth", availability: "In Stock", isNew: false, isTrending: true, isFeatured: true },
  { id: 23, name: "Silk Printed Stole", category: "Accessories", subCategory: "Accessories", price: 799, originalPrice: 1199, discount: 33, rating: 4.3, reviews: 39, sizes: ["Free Size"], colors: ["Pink","Beige"], image: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&h=1150&q=85", description: "A lightweight printed stole in a silk-blend weave, finished with hand-rolled edges.", material: "Silk blend", fit: "One size", brand: "KK Fashion", care: "Dry clean only", availability: "In Stock", isNew: true, isTrending: false, isFeatured: false },
  { id: 24, name: "Ivory Palazzo Set", category: "Ethnic Wear", subCategory: "Women", price: 2599, originalPrice: 3599, discount: 28, rating: 4.4, reviews: 55, sizes: ["S","M","L","XL"], colors: ["White","Beige"], image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&h=1150&q=85", description: "A flowing kurta-and-palazzo set in soft crepe, printed with a hand-drawn floral motif.", material: "Crepe", fit: "Relaxed fit", brand: "KK Fashion", care: "Hand wash cold", availability: "In Stock", isNew: false, isTrending: false, isFeatured: false },
  { id: 25, name: "Black Satin Slip Dress", category: "Dresses", subCategory: "Women", price: 2499, originalPrice: 3499, discount: 29, rating: 4.6, reviews: 133, sizes: ["S","M","L"], colors: ["Black"], image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&h=1150&q=85", description: "A bias-cut satin slip dress that skims the body, cut with adjustable straps for the right fall.", material: "Satin", fit: "Bias fit", brand: "KK Fashion", care: "Dry clean only", availability: "In Stock", isNew: true, isTrending: true, isFeatured: true },
  { id: 26, name: "Rust Handloom Cotton Saree", category: "Sarees", subCategory: "Women", price: 3299, originalPrice: 4599, discount: 28, rating: 4.5, reviews: 47, sizes: ["Free Size"], colors: ["Beige","Black"], image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&h=1150&q=85", description: "A handloom cotton saree with a contrast temple border, woven by artisan cooperatives.", material: "Handloom cotton", fit: "5.5m saree with blouse piece", brand: "KK Fashion", care: "Hand wash cold, separately", availability: "In Stock", isNew: false, isTrending: false, isFeatured: false },
];

/* ---------- Helper functions used across pages ---------- */

function kkFormatPrice(value) {
  return "₹" + Number(value).toLocaleString("en-IN");
}

function kkGetProductById(id) {
  return KK_PRODUCTS.find(p => p.id === Number(id));
}

function kkGetRelatedProducts(product, count = 4) {
  return KK_PRODUCTS
    .filter(p => p.id !== product.id && p.category === product.category)
    .slice(0, count);
}

function kkStarString(rating) {
  const full = Math.floor(rating);
  const half = rating - full >= 0.5;
  let stars = "★".repeat(full);
  if (half) stars += "½";
  return stars;
}

/* Sample review data, keyed by product id (falls back to generic set) */
const KK_REVIEWS = {
  default: [
    { name: "Ananya Sharma", rating: 5, date: "2 weeks ago", text: "Fabric quality is genuinely better than I expected at this price. Fit was true to size and stitching felt premium." },
    { name: "Rohan Mehta", rating: 4, date: "1 month ago", text: "Great everyday piece — colour matches the photos closely. Delivery took a couple of days longer than expected." },
    { name: "Priya Nair", rating: 5, date: "1 month ago", text: "Ordered for a wedding function and got so many compliments. Will definitely shop here again." },
    { name: "Karan Verma", rating: 4, date: "2 months ago", text: "Comfortable fit and the packaging was neat. Sizing runs slightly generous, so consider one size down." },
  ]
};

function kkGetReviews(productId) {
  return KK_REVIEWS[productId] || KK_REVIEWS.default;
}
